@usersp = http://localhost:3000/user/usersp
@logIn = http://localhost:3000/user/login
@getMaterias = http://localhost:3000/user/getData
@addMateria = http://localhost:3000/user/addMateria
@cursar = http://localhost:3000/user/cursar
@getMateriaById = http://localhost:3000/user/getMateriaById

### Loguear usuario
POST {{logIn}}
Content-Type: application/json

{
  "dni": "324",
  "pass": "123456"
}

### Crear usuario
POST {{usersp}}
Content-Type: application/json

{
  "nombre": "sadasd",
  "dni": "324",
  "correo": "crrr",
  "pass": "123456"
}

### Obtener materias 
GET {{getMaterias}}
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMjQiLCJpYXQiOjE3MTg1MTQ0NTd9.lD5sOeH87R1_xJQFYfdLXPEAx5Ofa-QelFQOUQq_0eI

### Añadir materia
POST {{addMateria}}
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMjQiLCJpYXQiOjE3MTg1MTQ0NTd9.lD5sOeH87R1_xJQFYfdLXPEAx5Ofa-QelFQOUQq_0eI

{
  "nombre_materia": "aaaaaagtgtaaaa"
}

### Relacionar usuario con materia
POST {{cursar}}
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMjQiLCJpYXQiOjE3MTg1MTQ0NTd9.lD5sOeH87R1_xJQFYfdLXPEAx5Ofa-QelFQOUQq_0eI

{
  "dni": "324",
  "idMateria": 32
}

### Obtener materias cursadas por un alumno 
GET {{getMateriaById}}/324
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMjQiLCJpYXQiOjE3MTg1MTQ0NTd9.lD5sOeH87R1_xJQFYfdLXPEAx5Ofa-QelFQOUQq_0eI
